### ISSUE TITLE
老司机，你不怕被查水表吗?

### ISSUE THREAD

**Issue by K-walker** [chendongde310/OTAKU#1]
厉害了，我的老司机，赶明儿就有人上门来查水表了，小心点啊，哥们！

**Comment by chendongde310** [comment]
本着学习的心态、批判的眼光、正直的价值观，我竟然看不到一点龌蹉下流之处，话说来都来了，难道兄台不点个star？

**Comment by K-walker** [comment]
@chendongde310  默默的给了你一颗星，有好资源及时2更新啊
